# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  pull_request:
    branches: ["main"]
jobs:
  build:
    env:
      privateenvarioment: ${{secrets.BOOTCAMP_TYPESCRIPT}}
      publicenvarioment: ${{secrets.GITHUB_TOKEN}}

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Mostrar mensaje"
        run: echo "Hola, mundo!"

      - name: "Mostrando variables de entorno"
        run: |
          echo "Esto es el valor de plataform: ${{ env.privateenvarioment }}"
          echo "Esto es el valor de plataform: ${{ env.publicenvarioment }}"